apiVersion: v1
kind: Namespace
metadata:
  name: flask-app
  labels:
    app.kubernetes.io/managed-by: jenkins
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    app.kubernetes.io/managed-by: helm
